# This is a sample build configuration for Scala.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#
# see https://confluence.atlassian.com/bitbucket/caching-dependencies-895552876.html
# for caches
image: bitbucketpipelines/scala-sbt:scala-2.12

pipelines:
  default:
    - step:
        name: Unit test
        script: # Modify the commands below to build your repository.
          - sbt clean test
        caches:
          - sbt
          - ivy2
  branches:
    master:
        - step:
            name: Coverage
            script: # Modify the commands below to build your repository.
              - sbt clean coverage test coverageReport
            caches:
              - sbt
              - ivy2